---
version: '3.8'

services:
  # Web application service
  web:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      labels:
        - "com.docker.stack.namespace=mystack"
        - "app=web"
    networks:
      - frontend
      - backend
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API service
  api:
    image: node:20-alpine
    command:
      - sh
      - -c
      - |
        cat > /tmp/server.js << 'EOF'
        const http = require('http');
        const server = http.createServer((req, res) => {
          if (req.url === '/health') {
            res.writeHead(200);
            res.end('OK');
          } else {
            res.writeHead(200);
            res.end('API Service Running');
          }
        });
        server.listen(3000, () => console.log('API listening on port 3000'));
        EOF
        node /tmp/server.js
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
      labels:
        - "com.docker.stack.namespace=mystack"
        - "app=api"
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - PORT=3000
    secrets:
      - source: api_secret_key
        target: /run/secrets/api_key
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis cache
  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "com.docker.stack.namespace=mystack"
        - "app=redis"
    networks:
      - backend
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Visualizer for Swarm
  visualizer:
    image: dockersamples/visualizer:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
      labels:
        - "com.docker.stack.namespace=mystack"
        - "app=visualizer"
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  frontend:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    attachable: true

volumes:
  redis_data:
    driver: local

configs:
  nginx_config:
    file: ./configs/nginx.conf

secrets:
  api_secret_key:
    external: true
